// Generated by CoffeeScript 1.7.1
(function() {
  var buddySystem;

  buddySystem = function(objs) {
    var o, s, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = objs.length; _i < _len; _i++) {
      o = objs[_i];
      s = String(o.innerHTML);
      if (s) {
        _results.push(o.innerHTML = s.replace(new RegExp('((?:[^ ]* ){' + ((s.match(/\s/g) || 0).length - 1) + '}[^ ]*) '), "$1&nbsp;"));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

}).call(this);
